services:
  tally:
    image: ghcr.io/kdscheuer/tally:latest
    ports:
      - "9200:9200"
    environment:
      - API_KEY=${API_KEY}                  # required
      # - METRIC_TTL=${METRIC_TTL}          # optional, default 1440 (minutes)
      # - MAX_METRICS=${MAX_METRICS}        # optional, default 1000
      # - PORT=${PORT}                      # optional, default 9200
      # - BIND_ADDRESS=${BIND_ADDRESS}      # optional, default 0.0.0.0
    restart: unless-stopped